version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV:-production}
    # volumes:
    #   - .:/app # bind mount . : folder inside the container
    #   - /app/node_modules # volume
    ports:
      - '3000:3000'
    env_file:
      - .env.${NODE_ENV:-production}  
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - '27018:27017'

volumes:
  mongo-data:
